- profiles/openasu/modules/custom/webspark_featurescustom/webspark_megamenu/css/webspark_megamenu.css
color change for home icon link
> Issue webspark 659 - color change for home icon link

- profiles/openasu/modules/webspark_featurescustom/webspark_megamenu/CHANGELOG.txt
- profiles/openasu/modules/webspark_featurescustom/webspark_megamenu/README.txt
- profiles/openasu/modules/webspark_featurescustom/webspark_megamenu/js/webspark_megamenu.js
Changes to Webspark MegaMenu feature. Includes changelog, readme, and megamenu js update.
> Issue webspark 737

- profiles/openasu/modules/custom/asu_dir/css/asu_dir_people_block.css
- profiles/openasu/modules/custom/asu_dir/css/asu_dir_tree.css
- profiles/openasu/modules/custom/asu_dir/js/widgets/asu_dirResultWidget.js
- profiles/openasu/modules/custom/asu_dir/theme/asu_dir.theme.inc
* removed column reserved for expertise areas in iSearch 
* increased size of title/name column in results
* moved all names/titles into alignment in results
* removed extra div in theming function
> WEBSPARK-765 - ASU Dir Styling Improvements

- profiles/openasu/modules/custom/asu_dir/css/asu_dir_people_block.css
- profiles/openasu/modules/custom/asu_dir/js/widgets/asu_dirResultWidget.js
* fix for profile images in search results, in windows below 992px
> NOJIRA - responsive styling fixes

- profiles/openasu/modules/custom/asu_dir/css/asu_dir_people_block.css
- profiles/openasu/modules/custom/asu_dir/js/asu_dir_ajax_solr_field.js
- profiles/openasu/modules/custom/asu_dir/js/widgets/asu_dirResultWidget.js
- profiles/openasu/modules/custom/asu_dir/js/widgets/asu_dirTreeWidget.js
- profiles/openasu/modules/custom/asu_dir/theme/asu_dir.tpl.php
- profiles/openasu/modules/custom/asu_dir/theme/asu_dir_ajax_solr_field.tpl.php
-  Added alt attributes to images
- Directory tree is now tabbable
-  Inputs now have titles 
- Buttons have hidden text
> WEBSPARK-778 - asu_dir accessibility fixes

- profiles/openasu/themes/innovation/templates/page.tpl.php
> WEBSPARK-772 - page template

- profiles/openasu/themes/innovation/templates/block--tb-megamenu--main-menu.tpl.php
Fixes Accessibility Issues:
- 2 of the "missing form label" errors originate with the ASU Brand header.
- 1 "empty button" error is from the mega menu
> WEBSPARK-781

- profiles/openasu/themes/innovation/templates/block--tb-megamenu--main-menu.tpl.php
> Webspark-781 - Removing button altogether rather than labeling it

- profiles/openasu/modules/webspark_featurescustom/asu_gsa/asu_gsa.module
- profiles/openasu/themes/innovation/css/innovation-main.css
- profiles/openasu/themes/innovation/js/innovation.js
- profiles/openasu/themes/innovation/templates/page.tpl.php
Nav menu now properly affixes to top when scrolling downwards, taking the mobile nav menu into account.
> Issue webspark 754

- profiles/openasu/openasu.make
-Nav menu affixes to top when scrolling down
-Handling the left placement of the admin menu
> WEBSPARK-754

- profiles/openasu/modules/webspark_featurescustom/webspark_panels_styles/plugins/styles/customstyles/css/customstyles.css
with the class space-bot-md. To prevent the badge from hitting the Megafooter menu items.
> WEBSPARK-812 - Add bottom padding to the megafoot columns

- profiles/openasu/themes/innovation/css/innovation-main.css
- Adding padding to the megafoot columns with the class .space-bot-md
> WEBSPARK-812

- profiles/openasu/modules/webspark_featurescustom/webspark_megamenu/css/webspark_megamenu.css
- profiles/openasu/modules/webspark_featurescustom/webspark_megamenu/js/webspark_megamenu.js
- profiles/openasu/themes/innovation/js/innovation.js
Updating the styling for Megamenu columns in order to standardize the look and feel of the Megamenu across more use cases.
> Issue webspark 777

- profiles/openasu/themes/innovation/css/innovation-main.css
-Part Deux: updating the background and border color
-Standardizing Megamenu Columns and adding coloring to children for differentiation
> WEBSPARK-777 

- profiles/openasu/modules/webspark_featurescustom/webspark_megamenu/css/webspark_megamenu.css
> Web Standards update for home icon font-sizing in megamenu. 

- profiles/openasu/modules/webspark_featurescustom/webspark_extras/webspark_extras.module
- profiles/openasu/modules/webspark_featurescustom/webspark_megamenu/css/webspark_megamenu.css
- profiles/openasu/modules/webspark_featurescustom/webspark_megamenu/js/webspark_megamenu.js
- profiles/openasu/modules/webspark_featurescustom/webspark_newsevents/webspark_newsevents.install
- profiles/openasu/themes/innovation/css/innovation-main.css
> WEBSPARK-821

- profiles/openasu/modules/webspark_featurescustom/webspark_megamenu/js/webspark_megamenu.js
- profiles/openasu/modules/webspark_featurescustom/webspark_panels_styles/plugins/styles/customstyles/css/customstyles.css
-Making sure the JS can only run when it makes sense
> WEBSPARK-820

- profiles/openasu/modules/custom/asu_rfi/asu_rfi.module
> WEBSPARK-834 - Prevent the RFI from hiding non-rfi forms from users

- profiles/openasu/modules/custom/asu_brand/asu_brand.admin.inc
-fix for empty version dropdown
> asu_brand module

- profiles/openasu/modules/webspark_featurescustom/mega_footer/mega_footer.module
https://asudev.jira.com/browse/WEBSPARK-1051
> WEBSPARK-1051 - Setting the Unit Title to optional in the Mega Footer

- profiles/openasu/modules/custom/asu_dirs/asu_dir_utilities/asu_dir_utilities.module
- profiles/openasu/modules/custom/asu_dirs/asu_dirs.info
- profiles/openasu/openasu.info
- Fix for drush si installation dependency ordering issue
> Webspark-1066

- profiles/openasu/modules/panopoly/panopoly_test/behat/features/image_widget.feature
- profiles/openasu/openasu.make
- profiles/openasu/patches/webspark-1066-panopoly-test-v143.patch
- profiles/openasu/patches/webspark-847_panopoly-test-137-update-v-1.43.patch
-fix for failing behat image_widget test
> WEBSPARK-1066 

- profiles/openasu/themes/innovation/template.php
> Webspark - 1066 

- profiles/openasu/themes/innovation/css/nav.css
> Issue webspark 1017

- profiles/openasu/modules/custom/asu_rfi/includes/asu_rfi.pages.inc
ASU RFI Grad Long Form causes search indexing to fatal error on cron
> Webspark 1124

- profiles/openasu/CHANGELOG.txt
> WEBSPARK 1.48 changelog-webspark-nevada

- profiles/openasu/modules/webspark_featurescustom/asu_spotlight/asu_spotlight.spotlight.inc
- profiles/openasu/modules/webspark_featurescustom/asu_spotlight/theme/asu_spotlight.theme.inc
- profiles/openasu/themes/innovation/css/buttons.css
- profiles/openasu/themes/innovation/css/innovation-main.css
> WEBSPARK-1140

- profiles/openasu/CHANGELOG.txt
- profiles/openasu/modules/custom/asu_rfi/asu_rfi.module
SI_dataLayer no longer works. Renaming to stay consistent with the rest of the university's GTM config, and to allow for proper tracking without custom GTM scripts.
> GTM Datalayer Reference Update

- profiles/openasu/modules/custom/asu_dirs/asu_dir/asu_dir.features.field_base.inc
- profiles/openasu/modules/custom/asu_dirs/asu_dir/asu_dir.features.field_instance.inc
- profiles/openasu/modules/custom/asu_dirs/asu_dir/asu_dir.features.inc
- profiles/openasu/modules/custom/asu_dirs/asu_dir/asu_dir.features.user_permission.inc
- profiles/openasu/modules/custom/asu_dirs/asu_dir/asu_dir.install
- profiles/openasu/modules/custom/asu_dirs/asu_dir/inc/asu_dir.field.inc
- profiles/openasu/modules/custom/asu_dirs/asu_dir/inc/asu_dir.helpers.inc
- profiles/openasu/modules/custom/asu_dirs/asu_dir/theme/asu_dir.theme.inc
- profiles/openasu/modules/custom/asu_dirs/asu_dir/theme/asu_dir_ajax_solr_field.tpl.php
Fixes syntax error in PHP 5.3.
> NOJIRA - removed short array syntax from ASU DIR

- profiles/openasu/modules/custom/asu_dirs/asu_isearch/CHANGELOG
- profiles/openasu/modules/custom/asu_dirs/asu_isearch/README.md
- profiles/openasu/modules/custom/asu_dirs/asu_isearch/asu_isearch.features.field_base.inc
- profiles/openasu/modules/custom/asu_dirs/asu_isearch/asu_isearch.features.field_instance.inc
- profiles/openasu/modules/custom/asu_dirs/asu_isearch/asu_isearch.field_group.inc
- profiles/openasu/modules/custom/asu_dirs/asu_isearch/asu_isearch.info
- profiles/openasu/modules/custom/asu_dirs/asu_isearch/asu_isearch.install
- profiles/openasu/modules/custom/asu_dirs/asu_isearch/asu_isearch.panelizer.inc
- profiles/openasu/modules/custom/asu_dirs/asu_isearch/inc/MigrateIsearchProfileMigration.inc
- profiles/openasu/modules/custom/asu_dirs/asu_isearch/inc/asu_isearch.panels.inc
- profiles/openasu/modules/custom/asu_dirs/asu_isearch/inc/asu_isearch.theme.inc
- profiles/openasu/modules/custom/asu_dirs/asu_isearch/theme/panels-pane--entity-field--node-field-isearch-video.tpl.php
asu_isearch 7.x-1.10
--------------------
- Fixed mapping of Twitter field for profile imports
- Fixed configuration for proper HTML field filtering
- Added profile video importing and display functionality
- Added asu_isearch_prepare_migration hook
- Fixed mapping of gradFaculties field for profile imports
> WEBSPARK-1270 - ASU LID bugfixes and improvements

- profiles/openasu/modules/webspark_featurescustom/mega_footer/CHANGELOG
- profiles/openasu/modules/webspark_featurescustom/mega_footer/css/megafoot.css
- profiles/openasu/modules/webspark_featurescustom/mega_footer/scss/_base.scss
- profiles/openasu/modules/webspark_featurescustom/uto_carousel/css/webspark_carousel.css
- profiles/openasu/modules/webspark_featurescustom/webspark_megamenu/CHANGELOG.txt
- profiles/openasu/modules/webspark_featurescustom/webspark_megamenu/css/webspark_megamenu.css
- profiles/openasu/themes/innovation/css/forms.css
- profiles/openasu/themes/innovation/css/innovation-main.css
- profiles/openasu/themes/innovation/css/nav.css
Accessibility changes to focus indicators in mega menu, uto_carousel, mega footer, and innovation theme
> WEBSPARK-1354 Focus Indicator Fixes

- profiles/openasu/modules/webspark_featurescustom/webspark_megamenu/js/webspark_megamenu.js
Change home <i> to <span> in webspark megamenu module
> WEBSPARK-1383

- profiles/openasu/openasu.make
Added patch for 1379 line to make file. Fixed incorrect path for 1304.
> 1304 and 1379 patch inclusion

- profiles/openasu/modules/contrib/tb_megamenu/templates/tb-megamenu-item.tpl.php
- profiles/openasu/openasu.make
Restoring Carets and Styles to TB MegaMenu module.
> WEBSPARK-1379

- profiles/openasu/modules/custom/asu_dirs/asu_isearch/CHANGELOG
- profiles/openasu/modules/custom/asu_dirs/asu_isearch/asu_isearch.info
- profiles/openasu/modules/custom/asu_dirs/asu_isearch/asu_isearch.install
- profiles/openasu/modules/custom/asu_dirs/asu_isearch/asu_isearch.module
- profiles/openasu/modules/custom/asu_dirs/asu_isearch/inc/MigrateIsearchProfileMigration.inc
- profiles/openasu/modules/custom/asu_dirs/asu_isearch/inc/asu_isearch.cron.inc
- profiles/openasu/themes/kalatheme/styles/kalacustomize/kalacustomize.inc
WEBSPARK-1455 - fix for asu_isearch module bloating queue database
WEBSPARK-1225 - fix for undefined index errors in kalacustomize theme
> WEBSPARK-1455, WEBSPARK-1225

- profiles/openasu/modules/custom/asu_rfi/includes/asu_rfi.pages.inc
Makes the Country field not required if the location is Online.
> Updated the logic to account for Online programs
